### ISSUE TITLE
`redux-saga-rxjs` support

### ISSUE THREAD

**Issue by tomkis1** [salsita/redux-elm#15]
What about get rid of redux-saga peerDep?
Figure out how?

**Comment by matthewgertner** [comment]
Talking to yourself?

**Comment by tomkis1** [comment]
Yes, anyway, let's investigate how `redux-observable` fits in since `redux-saga-rxjs` is technically dead.

**Comment by tomkis1** [comment]
to be landed in #36

**Comment by tomkis1** [comment]
Closing in favour of #36
