### ISSUE TITLE
Cancel saga after component is unmounted

### ISSUE THREAD

**Issue by lewtds** [salsita/redux-elm#19]
I see sagas are only started when mounting components but not stopped when they are unmounted. This can introduce data corruption when navigating from component C1 to component C2 of the same type.

**Comment by lewtds** [comment]
Wow. You're so fast! I was about to submit a similar patch (https://github.com/lewtds-forks/redux-elm/commit/3058d96e12cf1fd0954e5eb5d3a7c5f6a9286726) but then I saw this. And your code is better anyway. Thanks so much!

**Comment by tomkis1** [comment]
@lewtds sure, pushed and release `2.1.4`
