### ISSUE TITLE
effectExecutor not available after reducer replacement

### ISSUE THREAD

**Issue by namjul** [salsita/redux-elm#23]
I encountered a problem when using Webpacks HMR and replacing reducers.
The Problem is that the function used in
https://github.com/salsita/redux-elm/blob/master/src/storeEnhancer.js#L37 does not get applied after replace the reducer.
So when hot module replacement gets trigger all the sagas get cancelled but not re-initiated because all the actions don’t have an effectExecutor any more.

**Comment by tomkis1** [comment]
Fixed in 2.1.6
