### ISSUE TITLE
no HMR

### ISSUE THREAD

**Issue by jmarceli** [salsita/redux-elm#28]
Unfortunately HMR doesn't work, probably because of using stateless functions instead of React components. Are there any known workarounds for this issue?

Here is webpack log info:
```
[HMR] The following modules couldn't be hot updated: (They would need a full reload!)
log-apply-result.js:13 [HMR]  - 750
```

**Comment by tomkis1** [comment]
Are you using `redux-elm-skeleton` ? I am considering open-sourcing some `redux-elm-boilerplate` since people tend to have problems with stuff like that and I frankly have to admit that it's not easy to tackle.

Anyway, it does work for me in my project.

**Comment by jmarceli** [comment]
I've just cloned the `redux-elm-skeleton` and run: `npm i` followed by `npm start`. Then I made a small modification to `hello-world` view. This results in:

```
[HMR] The following modules couldn't be hot updated: (They would need a full reload!)
log-apply-result.js:13 [HMR]  - 684
```

**Comment by tomkis1** [comment]
@jmarceli I've just pushed [hmr](https://github.com/salsita/redux-elm-skeleton/tree/hmr) branch to `redux-elm-skeleton` where you can see how HRM could be set up  see this [commit](https://github.com/salsita/redux-elm-skeleton/commit/e69e6a1bf0e88a368d11ef1dec8c6c47d8b29ec7)

**Comment by jmarceli** [comment]
Fixed. Thanks.

**Comment by krzysztofpniak** [comment]
@tomkis1 why the commit you mentioned is not merged to master branch?

**Comment by faceyspacey** [comment]
webpack devserver is problematic. we should use webpack-hot-middleware and the latest version of react-hot-loader. It supports stateless functions.
