### ISSUE TITLE
Server-side rendering

### ISSUE THREAD

**Issue by kibin** [salsita/redux-elm#30]
I was looking at this project and while I was reading docs on gitbook I liked the idea, but had concerns with router and ssr. While I found [issue with examples of router integration](https://github.com/salsita/redux-elm/issues/27), I didn’t find anything about server-side rendering. Is it possible? Is there any tutorial on this?

**Comment by kibin** [comment]
I found [this comment](https://github.com/salsita/redux-elm/issues/29#issuecomment-225630396) (OT answer part) in an unrelated issue, so I guess it’s possible to do server-side rendering with redux-elm. So the main question that remains: how do you do it?

**Comment by tomkis1** [comment]
Yes it's indeed possible, the implementation is pretty straightforward and done like in any other `redux` project.

So [here is our company boilerplate](https://github.com/salsita/redux-boilerplate) which supports server side render as well as `react-native` client. The specific part related to server side render is [here](https://github.com/salsita/redux-boilerplate/blob/master/src/server/server.js#L44-L81).
