### ISSUE TITLE
Getting component path string

### ISSUE THREAD

**Issue by jmarceli** [salsita/redux-elm#42]
Hi,
Is it somehow possible to get component path described by action `type` inside that component view? It will be very helpful for naming forms in `redux-form` (ensuring unique name).

Example:
Application state structure: `root -> orders -> order`
Actions dispatched from `order` has type of: `Orders.Order.*'

Is it possible to generate `Orders.Order` string inside Order component view?
I didn't find any way of "extracting" that component path from dispatch method.

**Comment by tomkis1** [comment]
Would you need to display it in the UI? Or would you just need to store it in Model?

**Comment by jmarceli** [comment]
As for now I'm wrapping `reduxForm()` inside stateless function which gives me possibility to provide initial values based on redux-elm component model. Still I have no idea how to provide unique value for `form` key. Here is how it looks like:
```
const OrderFormWrapper = props => {
  const { data, dispatch, model } = props;
  // here both `dispatch` and `model` redux-elm props are available
  // but I have no idea how to "get" the component "path"

  const Form = reduxForm({
    initialValues: model2form(data),
    form: 'order', // <-- this should have unique value in case I want to create more than one order form
    fields: ['id', 'code', 'status'],
  })(OrderForm); // <-- OrderForm is an actual form component which need to be wrapped by reduxForm

  return (
    <Form {...props} />
  );
};
```

**Comment by tomkis1** [comment]
One option would be storing the information in the app state because every action (you'd use Mount here) holds action prefix

**Comment by jmarceli** [comment]
Thanks. I think that solves my issue.
For future reference here is the example code:
```
export const init = () => ({
  path: '', // here will be the path after component mounts
  // ... rest of the model initialization code
});

export default new Updater(init(), saga)
  .case('@@redux-elm/Mount', (model, { wrap }) => {
    // wrap variable has component path (with trailing dot) e.g. 'OrdersPage.Order.'
    // you may get rid of the dot with regex e.g. wrap.replace(/\.$/, '')
    return { ...model, path: wrap };
  })
  // ... other actions handled by this component
  .toReducer();
```
