### ISSUE TITLE
[docs] Explain multiple sagas with takeEvery 

### ISSUE THREAD

**Issue by jmatsushita** [salsita/redux-elm#43]
Hi there,

What's the `redux-elm` idiomatic way to route events to different sagas?

Right now I do this:
```
function* saga() {
  yield* takeEvery(['SOMETHING', 'OTHERTHING'], doTHINGS);
}
```

Where doTHINGS branches to `doSOMETHING` and `doOTHERTHING` but I'd like to write something like what case is doing such as:
```
function* saga() {
  yield* takeEveryCase()
    .case('SOMETHING', doSOMETHING)
    .case('OTHERTHING', doOTHERTHING)
}
```

Or a variation on this.

Am I missing something obvious?

**Comment by eliperelman** [comment]
@jmatsushita 

Typically I structure my reducer like the following for different action-to-saga handlers:

```js
import { takeEvery } from 'redux-saga';
import { fork } from 'redux-saga/effects';

function* doSomething() {
  // ...
}

function* doOtherThing() {
  // ...
}

function* listener() {
  yield [
    fork(takeEvery, 'SOMETHING', doSomething),
    fork(takeEvery, 'OTHERTHING', doOtherThing)
  ];
}

export default new Updater(init(), listener)
  .toReducer();
```

**Comment by jmatsushita** [comment]
A thing of beauty. Thanks!

**Comment by tomkis1** [comment]
This is certainly the right way to do it, however I do not think this should be part of the `redux-elm` docs, especially when I am planning to support `rxjs` as alternative saga implementation.

**Comment by tomkis1** [comment]
Closing, nothing actionable here.
