### ISSUE TITLE
Purpose of view wrapper?

### ISSUE THREAD

**Issue by dalgard** [salsita/redux-elm#52]
Does wrapping my component with `view()` to create a higher-order component serve any purpose in regard to composition/Elm architecture?

It looks like what it mainly does is dispatching mount/unmount actions and optimizing certain things, which are not essentially related to the fractal pattern.

**Comment by tomkis1** [comment]
> It looks like what it mainly does is dispatching mount/unmount actions and optimizing certain things, which are not essentially related to the fractal pattern.

You are absolutely right, it's there so that we can instantiate/deinstatiate fractal Sagas.

**Comment by dalgard** [comment]
How does that work, exactly?

I'm in the process of employing `redux-elm` in an enterprise front-end architecture, and it is important for me to understand the role of each piece.

**Comment by krzysztofpniak** [comment]
@dalgard the code is really short (~60LOC): https://github.com/salsita/redux-elm/blob/master/src/view.js
