### ISSUE TITLE
React context access

### ISSUE THREAD

**Issue by krzysztofpniak** [salsita/redux-elm#55]
How can I access React 'context'? https://facebook.github.io/react/docs/context.html
I'm trying to implement form library that is compatible with redux-elm and I would like to pass form name down to fields. I know it's not the best solutions, but at the moment I don't see any other options. Anyways, I realized that I cannot access react context inside components wrapped by view(). I took a look on the source code and it looks that you are not passing second parameter, and it seems to be the origin of my problem.

**Comment by namjul** [comment]
This should work independent of using view(). Context is not to be passed down. thats why they exist.

**Comment by tomkis1** [comment]
@namjul is right, basically you just need to define `contextTypes` and should be passing that automatically.
